flowchart TD
%% Nodes
    html("HTML")
    css("CSS")
    js("JS")
    
%% Edge connections between nodes
    html --> css --> js
%% Individual node styling. Try the visual editor toolbar for easier styling!
    
%% You can add notes with two "%" signs in a row!
